---

# enable  SPI
- name: Get SPI status
  shell: "raspi-config nonint get_spi"
  register: spi_status
  changed_when: False

- name: Print SPI status
  debug:
    msg: "SPI status is: {{ spi_status.stdout }}"

- name: Enable SPI
  become:  true
  shell: "raspi-config nonint do_spi 0"
  when: (spi_status.stdout != '0')

#install requirements for display(https://www.waveshare.com/wiki/1.44inch_LCD_HAT#Run_the_demo)
- name: download display driver
  get_url:
    url: https://www.airspayce.com/mikem/bcm2835/bcm2835-1.68.tar.gz
    dest: /home/pi/

- name: Extract archive
  ansible.builtin.unarchive:
    src: /home/pi/bcm2835-1.68.tar.gz
    dest: /home/pi
    remote_src: true

- name: install display driver
  become: true
  shell:
    cmd: "sudo ./configure && sudo make && sudo make check && sudo make install"
    chdir: /home/pi/bcm2835-1.68

- name: install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      #- python3-smbus
      - python3-rpi.gpio
      - python3-spidev
      - python3-numpy
      - python3-psutil
      - python3-pillow
      - libatlas-base-dev
      - libopenjp2-7


- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ usbmidihost_installDir }}"
    state: directory
    mode: '0755'

- name: copy files to dir
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ usbmidihost_installDir }}"
    owner: root
    mode: 755
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: copy service file
  become: true
  template:
    src: usbmidihost.service.j2
    dest: /lib/systemd/system/usbmidihost.service
    mode: 644
  notify:
    - reload systemctl

- name: start and enable service
  become: true
  service:
    name: usbmidihost.service
    state: started
    enabled: yes
